http:
  port: 8080 
admin:
  port: 9876
  host: localhost
log:
  level: debug

apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  seismicData:
    host: 'localhost'
    paths: '/seismic/*'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  seismic:
    url: 'https://65ca483b3b05d29307e01640.mockapi.io/api'

# Ensure these are declared as a list of strings
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy: # Removed the extra '-' from action to keep it under the same policy
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  seismic:
    apiEndpoints:
      - seismicData
    policies:
      - log: # This must match a name in the 'policies' list above
          - action:
              message: '${req.method} ${req.originalUrl}'
      - proxy:
          - action:
              serviceEndpoint: seismic
              changeOrigin: true